### PR TITLE
Raise `confluent-kafka` pin to `<=1.7.0`

### PR DESCRIPTION
**Pull request by l1nd3r0th**
Compared to last time (https://github.com/fyndiq/confluent_kafka_helpers/pull/63) this upgrade has fewer features/changes that seem applicable our use cases:

https://github.com/confluentinc/confluent-kafka-python/blob/master/CHANGELOG.md#v170
https://github.com/edenhill/librdkafka/releases/tag/v1.7.0

### CODE REVIEW

**Comment by aericson** [comment]
Should we do this now that we have tested in?

**Comment by gpkc** [comment]
Since we want to release this should we bump setup.py etc?

**Review by gpkc — APPROVED** [review]

**Review by vipin030 — APPROVED** [review]
👍

**Comment by l1nd3r0th** [comment]
> Since we want to release this should we bump setup.py etc?

:+1: 

I'll bump to `0.10.0`. We haven't released `0.9.0` yet, so we should release both IMO.

**Pull request merged**
